---
- hosts: jenkins
  become: true
  tasks:

  - name: Install java
    apt: 
      name: default-jre
      update_cache: yes

  - name: Import Jenkins CI key
    apt_key:
      url: https://pkg.jenkins.io/debian/jenkins.io.key
      state: present

  - name: Append the Debian package repository
    command: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

  - name: install jenkins
    apt:
      name: jenkins
      state: present
      update_cache: yes

  - name: Start jenkins service
    service:
      name: jenkins
      state: started

  - name: Allow port 8080
    ufw:
      rule: allow
      port: 8080

  - name: copy local config to remote
    copy:
      src: jenkins.alexismateo.net
      dest: /etc/nginx/sites-available/jenkins.alexismateo.net

  - name: Create symlink to jenkins.alexismateo.net
    file: 
      src: /etc/nginx/sites-available/jenkins.alexismateo.net 
      dest: /etc/nginx/sites-enabled/jenkins.alexismateo.net
      state: link
      force: true
    notify: nginx reload
